repository: ghojeong/ghojeong.github.io
favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: 고정완
title: 백엔드 개발자
email: rhwjddhks@gmail.com
email_title: 📮
phone: 010-3878-1459
phone_title: 📞

# Dark Mode (true/false/never)
darkmode: never

# About Section
about_title: 소개
about_profile_image: https://avatars.githubusercontent.com/u/38595650
about_content: | # this will include new lines to allow paragraphs
  자신있는 기술: Spring, JPA, Spring Security

  6년차 개발자 고정완입니다.
  
  백엔드 테크리드로 일하며 다음과 같은 성과를 냈습니다.
    - IDC에서 AWS 클라우드로 인프라 전환 후 <mark>장애빈도 99%</mark> 감소
    - 쿼리튜닝과 DB 파티셔닝 후 <mark>서버비용 82%</mark> 절약
    - 모놀리식에서 MSA로 리팩토링 후 테스트커버리지 86% 달성
    - 인증서버를 세션기반에서 토큰기반으로 변경 후 인증시간 93% 단축

content:

  - title: 학력
    layout: list
    content:
      - title: 울산과학기술원
        sub_title: 컴퓨터공학 성적우수 졸업
        caption: 수리과학 부전공
        description: |
          - 알고리즘 A+, 데이터구조 A, 데이터베이스 A-, 운영체제 A-, 네트워크 A-
          - 선형대수학 A, 미분방정식 A, 집합론 A, 이산수학 A, 위상수학 A, 통계학 A-
          - [NECSST](https://next.cs.vt.edu/) 연구실에서 Aggregated Data Center 연구에 참여

  - title: 실무경험 (6년차)
    layout: list
    content:
      - title: 백엔드 테크리드
        sub_title: Dreamfora
        caption: 2021.08.25 - 
        description: |
          - 사용기술: Java, Spring Boot, Spring Security, JPA, MariaDB
          - 미국, 영국, 인도, 러시아, 이집트 등 전세계 200만명이 사용하는 B2C 목표관리 앱을 개발
          - [**Dreamfora 경력기술서 링크**](https://github.com/ghojeong/resume/blob/main/dreamfora/README.md)

      - title: 웹 개발자
        sub_title: Ecube Labs
        caption: 2018.10.15 - 2020.12.28
        description: |
          - 사용기술: TypeScript, React, Redux, Express.js
          - 미국 볼티모어, 일본 이치카와, 한국 고양시와 계약한 B2B스마트 시티 SaaS 를 개발
          - [Ecube Labs 경력기술서 링크](https://github.com/ghojeong/resume/blob/main/ecubelabs/README.md)

  - title: 교육경험
    layout: list
    content:
      - title: 세미나 강사
        sub_title: 한빛미디어
        caption: 2019.03 - 2019.06
        description: |
          - [개발 문서화](http://www.hanbit.co.kr/store/education/edu_view.html?p_code=S3414110334)를 주제로 한빛미디어의 후원을 받아 공감세미나 주니어를 개최
          - 작성하는 법을 강의한 개발문서들
            - 사전정의서
            - 요구사항 명세서
            - Entity Relationship Diagram
            - 프로세스 Flow Chart

      - title: Kotlin 강사
        sub_title: 우아한테크코스
        caption: 2024.02 - 2024.06
        description: |
          - <mark>우아한테크코스</mark>에서 크루들에게 Kotlin, OOP, TDD 를 교육
          - 코드리뷰 예시
            - [람다와 함수형 프로그래밍](https://github.com/woowacourse/kotlin-omok/pull/55#discussion_r1535278325)
            - [테스트와 예외처리](https://github.com/woowacourse/kotlin-lotto/pull/93#issuecomment-1970238649)

      - title: Spring JPA 강사
        sub_title: 넥스트스텝
        caption: 2021.03 - 
        description: |
          - 현직자를 교육하며 WAS 와 ORM 프레임워크를 바닐라 언어만으로 구현하도록 지도
          - 코드리뷰 예시
            - [쿠키에 NullObjectPattern 도입](https://github.com/next-step/java-http/pull/43#discussion_r1676799820)
            - [멀티쓰레드에서의 영속성 컨텍스트](https://github.com/next-step/jpa-entity-manager/pull/39#discussion_r1372620312)

  - title: Dreamfora 경력기술
    layout: list
    content:
      - title: 클라우드 전환
        sub_title: 장애빈도 99% 감소
        caption: 이중화, 망분리, CI/CD
        description: |
          - 문제: IDC 인프라에 문제가 생기면 서비스가 정지
          - 원인: Single Point of Failure 가 되는 물리적 서버가 존재
          - 해결책: 클라우드로 인프라 이전 후 보강
            - 트래픽 폭증 시 서비스가 정지할 수 있는 WAS 서버를 이중화
            - 취약점 공격 시 데이터가 위험한 DB 를 Private Cloud 설정을 통해 인터넷과 격리
            - Continuous Integration 시, 빌드와 테스트 성공 여부를 확인
            - 도커 이미지를 활용한 Rolling 방식의 무중단 배포 도입

          <img src="images/dreamfora_crash.png" width="450px" />

      - title: MSA 도입
        sub_title: 테스트 커버리지 86% 달성
        caption: 서비스마다 인프라를 커스텀
        description: |
          - 문제: 신규 기능 추가 시, QA 에서 찾지 못하는 버그가 발생
          - 원인: 모놀리식 구조라 의도치 않은 Side Effect 가 발생
          - 해결책: 도메인을 기준으로 서비스를 분리
            - 모놀리식 서버를 5개의 도메인을 기준으로 분리 후 테스트 작성
              - 도메인 객체에는 단위 테스트를, 서비스 시나리오에는 인수 테스트를 작성
            - 분리한 5개의 마이크로 서비스 설명
              - Auth 서비스 (사용자 인증 및 인가)
              - Diary 서비스 (데이터를 자동 동기화)
              - Feed 서비스 (커뮤니티에 일상을 공유)
                - 로드밸런서를 통한 <mark>이중화와 자동복구</mark> 도입
              - Point 서비스 (이벤트성, 현금성 포인트)
                - <mark>Private Clould</mark> 로 망분리
              - Shop 서비스 (Point 를 소비하여 아이템을 거래)

          <img src="images/dreamfora_msa.png" width="450px" />

      - title: 테이블 스키마 재설계 및 쿼리튜닝
        sub_title: 서버비용 82% 절약
        caption: Horizontal Partitioning
        description: |
          - 문제: 게시글 검색 시 메모리와 CPU 자원을 많이 소모
          - 원인: 검색 시 탐색하는 테이블의 크기가 큼
          - 해결책: 주 단위로 테이블을 파티셔닝
            - 활성 테이블에는 1주일 동안 생성된 데이터만 남기고, 나머지는 분리한 테이블로 이동
            - 1달(5주)이 지난 데이터는 비용이 싼 아카이빙 스토리지 서버로 이동하여 비용절감
            - 활성 테이블이 아닌 테이블은 Pagination 을 통해 과거 데이터를 찾는 경우에만 사용

          <img src="images/dreamfora_dollar.png" width="500px" />

      - title: 데이터 마이그레이션
        sub_title: 마이그레이션 정합성 검증
        caption: JPA 기반의 테스트 코드
        description: |
          - 문제: 테스트로 마이그레이션 후 장애가 발생
          - 원인: 데이터 정합성이 맞지 않아 서버 로직이 오동작
          - 해결책: 마이그레이션 로직을 테스트 코드로 검증
            - 마이그레이션 로직을 JPA 로 작성해 JUnit 으로 검증
            - Batch Size 보다 데이터가 많아서 생긴 N+1 쿼리문제를 EntityManager 커스텀으로 해결

      - title: 토큰 기반 인증 도입
        sub_title: 인증시간 93% 단축
        caption: JWT 도입
        description: |
          - 문제: 인증 시 평균 8초가 넘는 시간이 소요
          - 원인: 지나치게 누적된 세션으로 인한 메모리 점유
            - Session TTL 설정이 잘못되어, 8천만개의 세션이 휘발되지 않고 쌓임
          - 해결책: JWT 를 활용해 Sessionless 인증 도입

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
